##### numpy手册链接
[Numpy库的手册](https://numpy.org/doc/stable/user/index.html)


In [1]:
import numpy as np

#1. 数组的创建
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))    #numpy.ndarray
arr_2=np.array([[1,2,3],[4,5,6]])
print(arr_2)
print(type(arr_2))    #numpy.ndarray
print("数组形状",arr_2.shape)    #(numpy.ndarray名称).属性/内部变量  (numpy.ndarray名称).函数()


[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
数组形状 (2, 3)


In [2]:
#2. 数组的索引和切片
print(arr[0])
print(arr[1:3])
print(arr_2[0,1])
print(arr_2[0:1])
print(arr_2[:][1])
print(arr_2[0:2,1:3])


1
[2 3]
2
[[1 2 3]]
[4 5 6]
[[2 3]
 [5 6]]


In [3]:
#3. 数组的运算
print([1,2,3]+[4,5,6])
print(np.array([1,2,3])+np.array([4,5,6]))    #向量相点加
print(np.array([1,2,3])*np.array([4,5,6]))    #向量相点乘


[1, 2, 3, 4, 5, 6]
[5 7 9]
[ 4 10 18]


In [4]:
#4. 数组的形状操作
import numpy as np
arr=np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
print(arr.shape)
new_arr=arr.reshape(2,6)    #改变形状
print(new_arr,"新的形状",new_arr.shape)

new_arr_2=new_arr.transpose()    #转置
print(new_arr_2)


(4, 3)
[[1 2 3 2 3 4]
 [3 4 5 4 5 6]] 新的形状 (2, 6)
[[1 3]
 [2 4]
 [3 5]
 [2 4]
 [3 5]
 [4 6]]


In [5]:
#5. 数组的线性代数运算
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr1_dot_arr2=np.dot(arr1,arr2) #数组的点积
arr1_cross_arr2=np.cross(arr1,arr2) #数组的叉积
print(arr1_dot_arr2)
print(arr1_cross_arr2)

#均值
print("数组平均值",np.mean(arr1))    #求数组平均值
print("数组平均值",arr1.mean())    #两种方式都可以---既是数组中的函数,也是numpy的函数

#最值
print("数组最小值",np.min(arr1))    #求数组最小值---每行进行排序
print("数组最小值",arr1.min())    #两种方式都可以
print("数组最大值",np.max(arr1))    #求数组最大值
print("数组最大值",arr1.max())    #两种方式都可以

#标准差
print("数组标准差",np.std(arr1))    #求数组标准差
print("数组标准差",arr1.std())    #两种方式都可以

#排序
print("数组排序",np.sort(arr1))    #对数组进行排序
#print("数组排序",arr1.sort())    #不可以---不是数组内部函数,但是是numpy的函数

print(arr1>2)    #数组元素是否大于2,结果是布尔数组
print(arr1[arr1>2])    #数组中大于2的元素---得到一个大于2的元素组成的数组
print(arr[((arr)>2) & ((arr)<5)])


32
[-3  6 -3]
数组平均值 2.0
数组平均值 2.0
数组最小值 1
数组最小值 1
数组最大值 3
数组最大值 3
数组标准差 0.816496580927726
数组标准差 0.816496580927726
数组排序 [1 2 3]
[False False  True]
[3]
[3 3 4 3 4 4]


In [6]:
#保存和导入
import numpy as np
arr=np.load("arr.npy")
print(arr)
np.save("arr_save",arr)

FileNotFoundError: [Errno 2] No such file or directory: 'arr.npy'

用numpy创建4*4的矩阵,只保留10以内的数,并计算所有元素之和

In [61]:
import numpy as np
np.random.seed(123456)    # 设置随机数种子
print(np.random.rand())
print(np.random.randint(low=1, high=10))    #生成随机整数在low和high之间的数
print(np.random.rand(3))    #生成3个随机数
arr=np.random.randint(low=0,high=100,size=16)
arr=arr.reshape(4,4)    #将数组变形为4行4列
print(arr)
print(arr[arr<=10])
print(np.sum(arr[arr<=10]))    #求数组中小于等于10的元素的和


0.12696983303810094
3
[0.89812542 0.70582013 0.7788297 ]
[[32 87 36  8]
 [74 10 12 75]
 [20 47 50 86]
 [34 14 70 42]]
[ 8 10]
18
